baseurl = "https://vincent.is/"
title = "Vincent Prouillet"
languageCode = "en-gb"
author = "Vincent Prouillet"

# Code highlighting
PygmentsCodeFences = true
pygmentsuseclasses = true
pygmentsstyle = "monokai"

googleAnalytics = "UA-43335571-1"
