title = "Vincent Prouillet: Developer & Entrepreneur"
base_url = "https://www.vincentprouillet.com"

generate_rss = true
highlight_code = true
compile_sass = true
# check_external_links = true
highlight_theme = "cheerfully-light"

[link_checker]
skip_anchor_prefixes = [
    "https://github.com/",
]

[extra]
author = "Vincent Prouillet"
